### ISSUE TITLE
Record / Read map interactions are backwards.

### ISSUE THREAD

**Issue by ZenDragonX** [shudnal/NomapPrinter#6]
Creating your map (drawing it) should happen when you interact with the box of items on the cartography table labeled "Record discoveries."   Likewise pressing the "Read map" area of the table should show the interactive map (if config option is set or display the created static map if config option is not set).

It's logically backwards the way it is now.  Confusing and not intuitive.

Suggested fix:  A config option to reverse the functionality between the two zones.  The box of stuff should draw/create the map.  The big open map area should "read / open" the map for viewing.

**Comment by shudnal** [comment]
Right now
- "Write" table part opens original map to change your pins.
- "Read" part is for generating the map. That's also historical part for "Map Printer" mod.
- "Map" hotkey is for showing the map.

Pls feel free to fork and adapt the mod for your needs.

**Comment by ZenDragonX** [comment]
OK, I hear your point.  It just seems confusing that I have to click on the "write" part of the table in order to read/view the map and then click the "read" part of the table to write (generate, create) the map.  Since clicking on the "write" part to change pins means I have to click it again on the "write" part after I am done changing my pins so that they get written, meaning I have to open the map to read it twice so my changes are saved before I click on the "read" part to write/draw my map.  It's very confusing.

A simple fix would be to have the interactive map appear on the "read" part of the table since I am reading it. Then have the generation of the map happen on the "write" side of the table, since generation is writing.

I would do it if I could but I am not as good a programmer as you. :(

**Comment by shudnal** [comment]
Interactive map showed on record discoveries is not a main goal of the mod. I've implemented it because someone asked and the "Record discoveries" part was free. So generally the interactive map was not needed much in nomap mode. 

The main usable and largest part of the map table is read section so it's natural for it to used as main functionality of the mod.

Also lore-wise you are reading the map from the table and simultaniously you are creating (drawing) your own copy of the map.

However I think it wouldn't be so bad if I implement the "part swapping" setting in the next update.

**Comment by ZenDragonX** [comment]
Just saw your updates!  Awesome job!  Thank you :)
