### ISSUE TITLE
Feature Request: Native map screen capture as static map

### ISSUE THREAD

**Issue by ZenDragonX** [shudnal/NomapPrinter#7]
Hey, love this mod! Fantastic work!

I was just wondering if you could add another map save type:  Native Map Capture.  The native map is really beautiful.  I wish I could just take a snapshot of it and save it as a png and use that as the static map instead of the generated algorithm one that takes a long time to generate and isn't as pretty (in my opinion) as the native in game map.  It would need to turn off the clouds when grabbing the screenshot, they would just be in the way.  Player pins are already in place (config option to hide other player's pins) also hide the local and multiplayer location pins.  

Then turn the whole thing into a png that can be zoomed and panned using the existing static map viewer that you already have.  I feel like this would take a fraction of a second to render since it's just grabbing an existing memory structure.  It would speed the whole map drawing process up and look nice too!

If it's possible to do this I would be really happy to send you some beer/coffee money donation :)

Thanks again for adding that swap button! Happy Holidays!

**Comment by shudnal** [comment]
Got it in version 1.1.1

**Comment by ZenDragonX** [comment]
Wow!  Great job! Thank you!

Three small issues: 1. Is there any way to turn off the fog layer that makes a distinction between your explored area and the area explored by others so that it all appears as the same unobstructed clarity without the fog distinction between the two area types?  I hope I am making sense, I don't know what you call that distinction.  2. any way to adjust the pin scale?  They seem a little bit large.  Perhaps a config option PinScale?  3.  Is there a way to make the map render as always daytime?  If you draw the map at night then it is very dark in the png.

Storage Question:

File size may be a concern.  I noticed that it saves a 15MB file on Normal.  I don't know if that saves locally or on the server.  I use ServerSideChars so I have the config setup to save locally in a file in order to keep the character data small and I am still testing so I haven't deployed this yet to the server.  If it saves the map locally to a file even when playing online and it's non-blocking (so the game doesn't freeze up when saving) then 15MB is not an issue.  How does it operate when playing on a server?  Does it save the map data locally or does it try to save it on the server when LocalFolder storage option is set?

Also, how can I send you a donation?

**Comment by shudnal** [comment]
1. I have an idea how to get rid of that.
2. Pins default size is 64x64. Normal map size is 4096x4096, Detailed and smooth is 8192x8192. And pins are resized 16x16 and 32x32 accordingly. If you add 16x16 pin on big map it's too small. And if you try to use non int value for scale it becomes blurry due to resize algorythm and small size of original image. Current size is compromise. I'll try to do something though.
3. I coudn't figure out how to manage it yet without noticable changing current time of day. As you mentioned earlier the way of getting current vanilla map is actually getting a snapshot of current shader state which depends on time of day. I've tried to swap sun position and color for 1 frame when map is formed. But it was pointless. Maybe I do something wrong.

Storage now have a distinct option to control where you want to save the data.
Character is to save all data to character save file. It have negative effect on servers with ServerCharacters' backups enabled.
So there is Local folder option allowing you to save the data in the png at the user's LocalLow game subfolder. That way nothing goes to server and every map stored locally on the client.
I have optimised map saving to not freezing the game as it was previously. Now even Smooth Vanilla map size ~80MB will save almost without freeze.

I don't think you have a way do send me any money as I from Russia and direct transactions are blocked. Pls don't bother. I do it for fun.

**Comment by ZenDragonX** [comment]
Ahh right on, that makes perfect sense!  Thank you for all your efforts!  Really appreciate it.  I hope this war stuff ends soon and we can all be in peace again.  If you are ever in Asia let me know and I'll buy you a drink as thank you! :)

**Comment by shudnal** [comment]
I've managed this in 1.1.2
Shared map fog tint and pin scale are configurable at "Map style extended" settings group.

Last issue for Vanilla map style is that disabling clouds layer also disables pinky mistlands clouds. I have no idea how it works lol. I have only bruteforce solution at this moment.

**Comment by ZenDragonX** [comment]
Looks fantastic!  Great work! 

Are the pink mistlands clouds needed?  Looks like black to me, which is fine.  The biggest issue that I see is that if you generate the map at night it's a dark map and if you make it in the day it looks bright and correct.  

BTW:  You mentioned there should be no blocking freeze when generating maps or when saving the character but in my single player offline testing it definitely freezes for a second or two when generating the map and when saving the character.

**Comment by shudnal** [comment]
Night map should be fixed by now.
That brief freeze on table interaction is the least I can do. It freezes when large map texture reapplied. I don't think I can get rid of that. Everything else mod do works in background.
Also saving the character with map inside will freeze the game. It's on game's side though, [SmoothSave](https://valheim.thunderstore.io/package/Smoothbrain/SmoothSave/) may help.

**Comment by ZenDragonX** [comment]
I think I see why the game is freezing for a second when I save my character even though I have LocalPath storage option set:  When I was first testing I had it set to Character save and it saved inside my character file making it large.  Now that I have switched to LocalPath it still seems that the old map data is stuck on my character file.  Any way that I can purge the old data and bring my character file back down to normal size or do I need to delete the character and make a new one ?

**Comment by shudnal** [comment]
Old data will be purged automatically from character when you save character with Local folder activated.
